# Generated by Django 4.1.1 on 2023-01-02 07:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Debate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("candidate_name", models.CharField(max_length=200)),
                ("candidate_class", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Delegate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("status_in_school", models.CharField(max_length=200)),
                ("phone_number", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Exhibition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("candidate_name", models.CharField(max_length=200)),
                ("candidate_class", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Exhibition2",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("candidate_name", models.CharField(max_length=200)),
                ("candidate_class", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("post", models.CharField(max_length=200)),
                ("about", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="img")),
                ("slug", models.SlugField(default="", max_length=200)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Proprietor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("qualification", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=200)),
                ("occupation", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("candidate_name", models.CharField(max_length=200)),
                ("candidate_class", models.CharField(max_length=200)),
                ("candidate_image", models.ImageField(default="", upload_to="img")),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=200)),
                ("website", models.CharField(blank=True, max_length=200)),
                ("about", models.CharField(blank=True, max_length=200)),
                (
                    "school_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Nursery", "Nursery"),
                            ("Primary", "Primary"),
                            ("Secondary", "Secondary"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "state_government_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Approved", "Approved"),
                            ("Under", "Under Processing"),
                            ("No", "Not Yet Applied"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "federal_government_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Registered", "Registered"),
                            ("Not Registered", "Not Registered"),
                        ],
                        max_length=200,
                    ),
                ),
                ("cac_reg_number", models.CharField(blank=True, max_length=200)),
                (
                    "other_association",
                    models.CharField(
                        blank=True, choices=[("Y", "Yes"), ("N", "No")], max_length=200
                    ),
                ),
                ("association_details", models.CharField(blank=True, max_length=200)),
                ("school_code", models.CharField(blank=True, max_length=200)),
                ("lga_code", models.CharField(blank=True, max_length=200)),
                (
                    "ownership",
                    models.CharField(
                        choices=[("S", "Sole Proprietor"), ("P", "NoPartnership")],
                        max_length=200,
                    ),
                ),
                (
                    "local_government",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OS01", "Atakunmosa East Central LCDA"),
                            ("OS02", "Atakunmosa West"),
                            ("OS03", "Atakunmosa West Central"),
                            ("OS04", "Ayedaade"),
                            ("OS05", "Ayedaade South LCDA"),
                            ("OS06", "Ayedire"),
                            ("OS07", "Ayedire South LCDA"),
                            ("OS08", "Boluwaduro"),
                            ("OS09", "Boluwaduro East LCDA"),
                            ("OS10", "Boripe"),
                            ("OS11", "Boripe North LCDA"),
                            ("OS12", "Ede East LCDA"),
                            ("OS13", "Ede North"),
                            ("OS14", "Ede North Area Council"),
                            ("OS15", "Ede South"),
                            ("OS16", "Egbedore"),
                            ("OS17", "Egbedore Area Council"),
                            ("OS18", "Egbedore South LCDA"),
                            ("OS19", "Ejigbo"),
                            ("OS20", "Ejigbo South LCDA"),
                            ("OS21", "Ejigbo West LCDA"),
                            ("OS22", "Ife Central"),
                            ("OS23", "Ife Central West LCDA"),
                            ("OS24", "Ife East"),
                            ("OS25", "Ife North"),
                            ("OS26", "Ife North Area Council"),
                            ("OS27", "Ife North Central LCDA"),
                            ("OS28", "Ife North West LCDA"),
                            ("OS29", "Ife Ooye LCDA"),
                            ("OS30", "Ife South"),
                            ("OS31", "Ife South West"),
                            ("OS32", "Ifedayo"),
                            ("OS33", "Ifedayo Area Council"),
                            ("OS34", "Ifelodun"),
                            ("OS35", "Ifelodun North Area Council"),
                            ("OS36", "Ifelodun North LCDA"),
                            ("OS37", "Ila"),
                            ("OS38", "Ila Central LCDA"),
                            ("OS39", "Ilesa East"),
                            ("OS40", "Ilesa North East LCDA"),
                            ("OS41", "Ilesa West"),
                            ("OS42", "Ilesa West Central LCDA"),
                            ("OS43", "Irepodun"),
                            ("OS44", "Irepodun South LCDA"),
                            ("OS45", "Irewole"),
                            ("OS46", "Irewole North East LCDA"),
                            ("OS47", "Isokan"),
                            ("OS48", "Isokan South LCDA"),
                            ("OS49", "Iwo"),
                            ("OS50", "Iwo East LCDA"),
                            ("OS51", "Iwo West LCDA"),
                            ("OS52", "Obokun"),
                            ("OS53", "Obokun East LCDA"),
                            ("OS54", "Odo Otin"),
                            ("OS55", "Odo Otin North LCDA"),
                            ("OS56", "Odo Otin South LCDA"),
                            ("OS57", "Ola Oluwa"),
                            ("OS58", "Ola Oluwa South East LCDA"),
                            ("OS59", "Olorunda"),
                            ("OS60", "Olorunda Area Council"),
                            ("OS61", "Olorunda North LCDA"),
                            ("OS62", "Oriade"),
                            ("OS63", "Oriade South LCDA"),
                            ("OS64", "Orolu"),
                            ("OS65", "Orolu Area Council"),
                            ("OS66", "Osogbo"),
                            ("OS67", "Osogbo South LCDA"),
                            ("OS68", "Osogbo West LCDA"),
                        ],
                        max_length=200,
                    ),
                ),
                ("contact_person", models.CharField(blank=True, max_length=200)),
                ("slug", models.SlugField(default="", max_length=200)),
                ("logo", models.ImageField(upload_to="img")),
                (
                    "proprietor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="member.proprietor",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Schools",
                "ordering": ["school_name"],
            },
        ),
        migrations.CreateModel(
            name="Workshop",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workshop_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("year", models.CharField(default="", max_length=200)),
                ("date", models.CharField(default="", max_length=200)),
                ("venue", models.CharField(default="", max_length=200)),
                ("amount", models.CharField(default="", max_length=200)),
                (
                    "delegate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="member.delegate",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="member.school"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Workshops",
                "ordering": ["workshop_name"],
            },
        ),
        migrations.CreateModel(
            name="SSSCompetition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("competition_name", models.CharField(max_length=200)),
                ("quran", models.CharField(max_length=200)),
                ("teacher_name", models.CharField(max_length=200)),
                ("teacher_phone", models.CharField(max_length=200)),
                ("principal_name", models.CharField(max_length=200)),
                ("essay_writing", models.CharField(max_length=200)),
                ("debate", models.ManyToManyField(to="member.debate")),
                ("exhibition", models.ManyToManyField(to="member.exhibition2")),
                ("quiz", models.ManyToManyField(to="member.quiz")),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="member.school"
                    ),
                ),
            ],
            options={
                "ordering": ["school"],
            },
        ),
        migrations.CreateModel(
            name="PrimaryCompetition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("competition_name", models.CharField(max_length=200)),
                ("quran", models.CharField(max_length=200)),
                ("teacher_name", models.CharField(max_length=200)),
                ("teacher_phone", models.CharField(max_length=200)),
                ("principal_name", models.CharField(max_length=200)),
                ("khutbah", models.CharField(max_length=200)),
                (
                    "exhibition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="member.exhibition",
                    ),
                ),
                ("quiz", models.ManyToManyField(to="member.quiz")),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="member.school"
                    ),
                ),
            ],
            options={
                "ordering": ["school"],
            },
        ),
        migrations.CreateModel(
            name="JSSCompetition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("competition_name", models.CharField(max_length=200)),
                ("quran", models.CharField(max_length=200)),
                ("teacher_name", models.CharField(max_length=200)),
                ("teacher_phone", models.CharField(max_length=200)),
                ("principal_name", models.CharField(max_length=200)),
                ("pick_and_talk", models.CharField(max_length=200)),
                ("ceative_writing", models.CharField(max_length=200)),
                ("caligraphy", models.CharField(max_length=200)),
                ("quiz", models.ManyToManyField(to="member.quiz")),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="member.school"
                    ),
                ),
            ],
            options={
                "ordering": ["school"],
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surname", models.CharField(default="", max_length=200)),
                ("other_names", models.CharField(default="", max_length=200)),
                (
                    "student_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("3", "Grade 3"),
                            ("4", "Grade 4"),
                            ("5", "Grade 5"),
                            ("6", "Grade 6"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        default="",
                        max_length=200,
                    ),
                ),
                ("date_of_birth", models.DateTimeField()),
                (
                    "school",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="member.school",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Examination",
                "ordering": ["surname"],
            },
        ),
        migrations.CreateModel(
            name="CalenderRegistration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="member.school"
                    ),
                ),
            ],
            options={
                "ordering": ["-year"],
            },
        ),
    ]
