# Generated by Django 4.1.1 on 2022-11-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primarycompetition',
            name='quiz',
        ),
        migrations.AddField(
            model_name='primarycompetition',
            name='quiz',
            field=models.ManyToManyField(to='member.quiz'),
        ),
    ]
